import os
import time
import tkinter as tk
from tkinter import messagebox

root = tk.Tk()
root.withdraw()

print("Welcome to *Yes or No?*")
time.sleep(1)
os.system("clear")

time.sleep(1.5)
answ = input("Yes or No? ")

if answ.lower() == "yes":
  os.system("clear")
  print("Since you said " + answ)
  time.sleep(1)
  print("I will do *something*")
  time.sleep(2)
  os.system("clear")
  os.system('date "+%T"')
  time.sleep(2)
  os.system("clear")
  print("Did you like it? ")
  time.sleep(1)
  print("Take your time to think about your answer.")
  time.sleep(3.5)
  os.system("clear")
  answ2 = input("Yes or No? ")

  if answ2.lower() == "yes":
    print("Oh, really?")
    time.sleep(0.5)
    print("Thanks!")
    time.sleep(1)
    os.system("clear")
    print("I can do better!")
    time.sleep(1.5)
    os.system("clear")
    print("Ok, I'm ready..")
    time.sleep(1)
    os.system("clear")
    messagebox.showwarning('Look at me', 'I am also here!')
    time.sleep(1)
    print("Liked it?")
    time.sleep(0.5)
    print("I did :)")
    time.sleep(2)
    os.system("clear")
    print("B")
    print("O")
    print("Z")
    print("O")
    print("!")
    print("!")
    messagebox.showwarning('Lol', 'Catch me if you can bozo')
    messagebox.showwarning('xD', 'little trolley troll train troll')
    print("W")
    print("H")
    print("A")
    print("T")
    print("T")
    print("?")
    messagebox.showwarning('spawmmd', 'gotchacthahchahhhrth')
    messagebox.showwarning(
        'LMAO ROTL',
        'Hahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahah')
    print("W")
    print("H")
    print("A")
    print("T")
    print("T")
    print("?")
    messagebox.showwarning('Lol', 'Catch me if you can bozo')
    messagebox.showwarning('xD', 'little trolley troll train troll')
    print("W")
    print("H")
    print("A")
    print("T")
    print("T")
    print("?")
    messagebox.showwarning('spawmmd', 'gotchacthahchahhhrth')
    messagebox.showwarning(
        'LMAO ROTL',
        'Hahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahah')
    
    time.sleep(1)
    os.system("clear")
    print("Sorry :)")
    time.sleep(0.5)
    print("I got carried a bit")
    time.sleep(0.8)
    os.system("clear")
    print("I am sorry for the inconvenience")
    print("Let's go on with the fun stuff!")
    time.sleep(1)
    os.system("clear")
    print("i guess :)")
    time.sleep(0.1)
    os.system("clear")
    print("Ok so, i won't ask you if like the last *thing*")
    time.sleep(0.5)
    print("For obvious reasons")
    time.sleep(1)
    os.system("clear")
    print("Next *thing*!")
    time.sleep(0.5)
    os.system("clear")
    
    answ3=input("What is your name? ")
    time.sleep(1)
    os.system("clear")
    print("So your name is " + answ3)
    time.sleep(1.5)
    print("I guess that's, cool? or something..")
    time.sleep(2)
    os.system("clear")
    print("Nevermind that was awful")
    time.sleep(1)
    os.system("clear")
    print("Ok ok, i have an idea")
    time.sleep(1)
    os.system("clear")
    print("Basically, i will ask you a *HARD* question")
    time.sleep(0.5)
    print("And you will answer!")
    time.sleep(1)
    os.system("clear")
    aw=input("Answer: ")
    if answ.lower() == "yes":
      print("Ok ok, you got the hang of it")
      time.sleep(1)
      os.system("clear")
      print("That's cool, now i'll do *something* to reward you")
      time.sleep(1)
      os.system("clear")
      os.system("yes HAHAHA")
      os.system("yes littletroll")
      
    else:
      time.sleep(0.5)
      os.system("clear")
      time.sleep(1)
      print(":(")
      time.sleep(2)
      os.system("exit")

  else:
    time.sleep(0.5)
    os.system("clear")
    time.sleep(1)
    print(":(")
    time.sleep(2)
    os.system("exit")
else:
  time.sleep(0.5)
  os.system("clear")
  time.sleep(1)
  print(":(")
  time.sleep(2)
  os.system("exit")
